# Generated by Django 4.1.3 on 2022-12-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stores',
            name='Product',
        ),
        migrations.AddField(
            model_name='stores',
            name='products',
            field=models.CharField(default='', max_length=200, verbose_name='Products'),
        ),
    ]
